### ISSUE TITLE
Number of submissions to VAST 2016?

### ISSUE THREAD

**Issue by cscheid** [steveharoz/Vis-Acceptance-Rates#3]
We know the number of accepted papers from the website.

**Comment by steveharoz** [comment]
Not sure which number to use. (from https://www.computer.org/csdl/trans/tg/2017/01/07753095.pdf)

![image](https://cloud.githubusercontent.com/assets/2257540/24662096/cbd1b406-1919-11e7-918d-bdb5ba813398.png)

**Comment by steveharoz** [comment]
I'll just go with 157.
